CREATE TABLE supplier(
    SNO TEXT PRIMARY KEY,
    SNAME TEXT,
    STATUS INTEGER,
    CITY TEXT
);

INSERT INTO supplier (SNO, SNAME, STATUS, CITY) VALUES
('S1','SMITH',20, 'LONDON'),
('S2','JACOB',30, 'PARIS'),
('S3','LORA',2, 'PARIS'),
('S4','PETER',18, 'LONDON'),
('S5','MICHAEL',25, 'LONDON');

SELECT * FROM supplier;